Implement fenced_submit using texture readback
tangmi/gfx pull request #2
Opened 2019-05-01 22:24 UTC by MillerJames

This is not the "correct" way to implement fences, but it works for my purposes (blocking until pending work finishes, for performance tests)

PR checklist:
- [ ] `make` succeeds (on *nix)
- [ ] `make reftests` succeeds
- [ ] tested examples with the following backends:
- [ ] `rustfmt` run on changed code

2019-05-07 01:18 UTC, MillerJames commented
Needs better error handling, should not panic on failure.

2019-05-22 23:52 UTC, tangmi requested changes

2019-05-22 23:52 UTC, tangmi commented on src/backend/dx11/src/lib.rs
> +            let mut device = std::ptr::null_mut();
must release device :(

2019-05-22 23:52 UTC, tangmi commented on src/backend/dx11/src/lib.rs
> +            let mut device = std::ptr::null_mut();
Should we make a com object smart pointer wrapper??

2019-05-23 00:02 UTC, tangmi approved these changes

2019-05-23 00:02 UTC, merged